version: "3.8"

services:
  bot:
    build: .
    ports:
      - "9001:9001"
    container_name: hm-telegram-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alisa
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    networks:
      - backend

networks:
  backend:
    external: true
    name: project_backend
